# Generated by Django 4.0.3 on 2022-05-31 14:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('request_number', models.AutoField(primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=100)),
                ('parent_name', models.CharField(max_length=100)),
                ('school', models.CharField(max_length=100)),
                ('grade', models.CharField(max_length=100)),
                ('status', models.CharField(default='Pending', max_length=100)),
                ('resident_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='resident_number')),
            ],
        ),
        migrations.CreateModel(
            name='Residency',
            fields=[
                ('request_number', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(default='Pending', max_length=100)),
                ('resident_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='resident_number')),
            ],
        ),
        migrations.CreateModel(
            name='MaternalCare',
            fields=[
                ('request_number', models.AutoField(primary_key=True, serialize=False)),
                ('child_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('birth_place', models.CharField(max_length=100)),
                ('status', models.CharField(default='Pending', max_length=100)),
                ('resident_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='resident_number')),
            ],
        ),
        migrations.CreateModel(
            name='IndigencyClearance',
            fields=[
                ('request_number', models.AutoField(primary_key=True, serialize=False)),
                ('patient_relationship', models.CharField(max_length=100)),
                ('patient_name', models.CharField(max_length=100)),
                ('purpose', models.CharField(max_length=100)),
                ('passed_onto_whom', models.CharField(max_length=100)),
                ('status', models.CharField(default='Pending', max_length=100)),
                ('resident_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='resident_number')),
            ],
        ),
        migrations.CreateModel(
            name='IndigencyBurial',
            fields=[
                ('request_number', models.AutoField(primary_key=True, serialize=False)),
                ('deceased_relationship', models.CharField(choices=[('Father', 'Father'), ('Mother', 'Mother'), ('Son', 'Son'), ('Daughter', 'Daughter'), ('Others', 'Others')], max_length=100)),
                ('deceased_name', models.CharField(max_length=100)),
                ('passed_onto_whom', models.CharField(max_length=100)),
                ('status', models.CharField(default='Pending', max_length=100)),
                ('resident_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='resident_number')),
            ],
        ),
        migrations.CreateModel(
            name='Immunization',
            fields=[
                ('request_number', models.AutoField(primary_key=True, serialize=False)),
                ('mother_name', models.CharField(max_length=100)),
                ('father_name', models.CharField(max_length=100)),
                ('birth_height', models.FloatField(default=0)),
                ('status', models.CharField(default='Pending', max_length=100)),
                ('resident_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='resident_number')),
            ],
        ),
        migrations.CreateModel(
            name='Guardianship',
            fields=[
                ('request_number', models.AutoField(primary_key=True, serialize=False)),
                ('guardian_name', models.CharField(max_length=100)),
                ('status', models.CharField(default='Pending', max_length=100)),
                ('resident_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='resident_number')),
            ],
        ),
        migrations.CreateModel(
            name='DentalService',
            fields=[
                ('request_number', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(default='Pending', max_length=100)),
                ('resident_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='resident_number')),
            ],
        ),
        migrations.CreateModel(
            name='ConstituentID',
            fields=[
                ('request_number', models.AutoField(primary_key=True, serialize=False)),
                ('id_number', models.CharField(blank=True, max_length=100, null=True)),
                ('date_received', models.DateField()),
                ('signature', models.ImageField(null=True, upload_to='signature/%Y/%m/%D/')),
                ('picture', models.ImageField(null=True, upload_to='pic/%Y/%m/%D/')),
                ('is_paid', models.BooleanField(default=False)),
                ('status', models.CharField(default='Pending', max_length=100)),
                ('resident_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='resident_number')),
            ],
        ),
        migrations.CreateModel(
            name='Comelec',
            fields=[
                ('request_number', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(default='Pending', max_length=100)),
                ('resident_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='resident_number')),
            ],
        ),
        migrations.CreateModel(
            name='Cedula',
            fields=[
                ('request_number', models.AutoField(primary_key=True, serialize=False)),
                ('birth_place', models.CharField(max_length=100)),
                ('profession', models.CharField(blank=True, max_length=100, null=True)),
                ('monthly_income', models.CharField(blank=True, max_length=100, null=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('status', models.CharField(default='Pending', max_length=100)),
                ('resident_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='resident_number')),
            ],
        ),
        migrations.CreateModel(
            name='BusinessClosure',
            fields=[
                ('request_number', models.AutoField(primary_key=True, serialize=False)),
                ('business_name', models.CharField(max_length=100)),
                ('business_owner', models.CharField(max_length=100)),
                ('business_address', models.CharField(max_length=100)),
                ('business_nature', models.CharField(max_length=100)),
                ('last_business_operated', models.DateField()),
                ('status', models.CharField(default='Pending', max_length=100)),
                ('resident_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='resident_number')),
            ],
        ),
        migrations.CreateModel(
            name='BusinessClearance',
            fields=[
                ('request_number', models.AutoField(primary_key=True, serialize=False)),
                ('business_name', models.CharField(max_length=100)),
                ('business_owner', models.CharField(max_length=100)),
                ('business_address', models.CharField(max_length=100)),
                ('business_nature', models.CharField(max_length=100)),
                ('start_business_operated', models.DateField()),
                ('status', models.CharField(default='Pending', max_length=100)),
                ('resident_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='resident_number')),
            ],
        ),
        migrations.CreateModel(
            name='BuildingClearance',
            fields=[
                ('request_number', models.AutoField(primary_key=True, serialize=False)),
                ('maintenance_type', models.CharField(max_length=100)),
                ('status', models.CharField(default='Pending', max_length=100)),
                ('resident_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='resident_number')),
            ],
        ),
        migrations.CreateModel(
            name='BarangayClearance',
            fields=[
                ('request_number', models.AutoField(primary_key=True, serialize=False)),
                ('purpose', models.CharField(choices=[('Loan', 'Loan'), ('Others', 'Others')], max_length=10, null=True)),
                ('has_payment', models.BooleanField(default=False)),
                ('is_paid', models.BooleanField(default=False)),
                ('status', models.CharField(default='Pending', max_length=100)),
                ('resident_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='resident_number')),
            ],
        ),
        migrations.CreateModel(
            name='BailBond',
            fields=[
                ('request_number', models.AutoField(primary_key=True, serialize=False)),
                ('case_number', models.CharField(blank=True, max_length=100, null=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('status', models.CharField(default='Pending', max_length=100)),
                ('resident_number', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='resident_number')),
            ],
        ),
    ]
