# Generated by Django 4.0.3 on 2022-05-31 14:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Forms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bailbond',
            name='date_requested',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='date requested'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='barangayclearance',
            name='date_requested',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='date requested'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='buildingclearance',
            name='date_requested',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='date requested'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='businessclearance',
            name='date_requested',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='date requested'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='businessclosure',
            name='date_requested',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='date requested'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cedula',
            name='date_requested',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='date requested'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comelec',
            name='date_requested',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='date requested'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='constituentid',
            name='date_requested',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='date requested'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dentalservice',
            name='date_requested',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='date requested'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='guardianship',
            name='date_requested',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='date requested'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='immunization',
            name='date_requested',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='date requested'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='indigencyburial',
            name='date_requested',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='date requested'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='indigencyclearance',
            name='date_requested',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='date requested'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='maternalcare',
            name='date_requested',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='date requested'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='residency',
            name='date_requested',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='date requested'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='voucher',
            name='date_requested',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='date requested'),
            preserve_default=False,
        ),
    ]
