# Generated by Django 3.2.9 on 2022-03-05 12:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Forms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='resident_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='resident_number'),
        ),
        migrations.AddField(
            model_name='residency',
            name='resident_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='resident_number'),
        ),
        migrations.AddField(
            model_name='maternalcare',
            name='resident_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='resident_number'),
        ),
        migrations.AddField(
            model_name='indigencyclearance',
            name='resident_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='resident_number'),
        ),
        migrations.AddField(
            model_name='indigencyburial',
            name='resident_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='resident_number'),
        ),
        migrations.AddField(
            model_name='immunization',
            name='resident_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='resident_number'),
        ),
        migrations.AddField(
            model_name='guardianship',
            name='resident_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='resident_number'),
        ),
        migrations.AddField(
            model_name='dentalservice',
            name='resident_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='resident_number'),
        ),
        migrations.AddField(
            model_name='constituentid',
            name='resident_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='resident_number'),
        ),
        migrations.AddField(
            model_name='comelec',
            name='resident_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='resident_number'),
        ),
        migrations.AddField(
            model_name='cedula',
            name='resident_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='resident_number'),
        ),
        migrations.AddField(
            model_name='businessclosure',
            name='resident_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='resident_number'),
        ),
        migrations.AddField(
            model_name='businessclearance',
            name='resident_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='resident_number'),
        ),
        migrations.AddField(
            model_name='buildingclearance',
            name='resident_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='resident_number'),
        ),
        migrations.AddField(
            model_name='barangayclearance',
            name='resident_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='resident_number'),
        ),
        migrations.AddField(
            model_name='bailbond',
            name='resident_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='resident_number'),
        ),
    ]
