# Generated by Django 4.0.3 on 2022-05-31 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Forms', '0002_bailbond_date_requested_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bailbond',
            name='is_paid',
        ),
        migrations.RemoveField(
            model_name='barangayclearance',
            name='is_paid',
        ),
        migrations.RemoveField(
            model_name='cedula',
            name='is_paid',
        ),
        migrations.RemoveField(
            model_name='constituentid',
            name='is_paid',
        ),
        migrations.AddField(
            model_name='bailbond',
            name='document_name',
            field=models.CharField(default='Bail Bond', max_length=100),
        ),
        migrations.AddField(
            model_name='barangayclearance',
            name='document_name',
            field=models.CharField(default='Barangay Clearance', max_length=100),
        ),
        migrations.AddField(
            model_name='buildingclearance',
            name='document_name',
            field=models.CharField(default='Building Clearance', max_length=100),
        ),
        migrations.AddField(
            model_name='businessclearance',
            name='document_name',
            field=models.CharField(default='Business Clearance', max_length=100),
        ),
        migrations.AddField(
            model_name='businessclosure',
            name='document_name',
            field=models.CharField(default='Business Closure', max_length=100),
        ),
        migrations.AddField(
            model_name='cedula',
            name='document_name',
            field=models.CharField(default='Cedula', max_length=100),
        ),
        migrations.AddField(
            model_name='comelec',
            name='document_name',
            field=models.CharField(default='Comelec', max_length=100),
        ),
        migrations.AddField(
            model_name='constituentid',
            name='document_name',
            field=models.CharField(default='Constituent ID', max_length=100),
        ),
        migrations.AddField(
            model_name='dentalservice',
            name='document_name',
            field=models.CharField(default='Dental Service', max_length=100),
        ),
        migrations.AddField(
            model_name='guardianship',
            name='document_name',
            field=models.CharField(default='Guardianship', max_length=100),
        ),
        migrations.AddField(
            model_name='immunization',
            name='document_name',
            field=models.CharField(default='Immunization', max_length=100),
        ),
        migrations.AddField(
            model_name='indigencyburial',
            name='document_name',
            field=models.CharField(default='Indigency Burial', max_length=100),
        ),
        migrations.AddField(
            model_name='indigencyclearance',
            name='document_name',
            field=models.CharField(default='Indigency Clearance', max_length=100),
        ),
        migrations.AddField(
            model_name='maternalcare',
            name='document_name',
            field=models.CharField(default='Maternal Care', max_length=100),
        ),
        migrations.AddField(
            model_name='residency',
            name='document_name',
            field=models.CharField(default='Residency', max_length=100),
        ),
        migrations.AddField(
            model_name='voucher',
            name='document_name',
            field=models.CharField(default='Voucher', max_length=100),
        ),
    ]
