# Generated by Django 4.0.5 on 2022-06-09 17:53

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Forms', '0003_remove_bailbond_is_paid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constituentid',
            name='picture',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='constituentid',
            name='signature',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='image'),
        ),
    ]
