# Generated by Django 4.0.3 on 2022-04-02 08:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Forms', '0003_remove_bailbond_id_alter_bailbond_request_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bailbond',
            name='resident_number',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='resident_number'),
        ),
    ]
