# Generated by Django 4.0.3 on 2022-04-03 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Forms', '0004_alter_bailbond_resident_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barangayclearance',
            name='id',
        ),
        migrations.RemoveField(
            model_name='buildingclearance',
            name='id',
        ),
        migrations.RemoveField(
            model_name='businessclearance',
            name='id',
        ),
        migrations.RemoveField(
            model_name='businessclosure',
            name='id',
        ),
        migrations.RemoveField(
            model_name='cedula',
            name='id',
        ),
        migrations.RemoveField(
            model_name='comelec',
            name='id',
        ),
        migrations.RemoveField(
            model_name='constituentid',
            name='id',
        ),
        migrations.RemoveField(
            model_name='dentalservice',
            name='id',
        ),
        migrations.RemoveField(
            model_name='guardianship',
            name='id',
        ),
        migrations.RemoveField(
            model_name='immunization',
            name='id',
        ),
        migrations.RemoveField(
            model_name='indigencyburial',
            name='id',
        ),
        migrations.RemoveField(
            model_name='indigencyclearance',
            name='id',
        ),
        migrations.RemoveField(
            model_name='maternalcare',
            name='id',
        ),
        migrations.RemoveField(
            model_name='residency',
            name='id',
        ),
        migrations.RemoveField(
            model_name='voucher',
            name='id',
        ),
        migrations.AlterField(
            model_name='barangayclearance',
            name='request_number',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='buildingclearance',
            name='request_number',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='businessclearance',
            name='request_number',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='businessclosure',
            name='request_number',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cedula',
            name='request_number',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='comelec',
            name='request_number',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='constituentid',
            name='request_number',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='dentalservice',
            name='request_number',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='guardianship',
            name='request_number',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='immunization',
            name='request_number',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='indigencyburial',
            name='request_number',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='indigencyclearance',
            name='request_number',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='maternalcare',
            name='request_number',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='residency',
            name='request_number',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='request_number',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
