# Generated by Django 4.0.3 on 2022-04-04 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Forms', '0005_remove_barangayclearance_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bailbond',
            name='request_number',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
