# Generated by Django 4.0.3 on 2022-04-04 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Forms', '0006_alter_bailbond_request_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bailbond',
            name='request_number',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
