# Generated by Django 4.0.3 on 2022-04-07 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Forms', '0007_alter_bailbond_request_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='immunization',
            name='birth_height',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='indigencyclearance',
            name='patient_relationship',
            field=models.CharField(max_length=100),
        ),
    ]
