# Generated by Django 4.0.3 on 2022-04-07 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Forms', '0008_alter_immunization_birth_height_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher',
            name='grade',
            field=models.CharField(max_length=100),
        ),
    ]
