# Generated by Django 4.0.3 on 2022-04-11 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Forms', '0010_remove_bailbond_case_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bailbond',
            name='case_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
