# Generated by Django 3.2.3 on 2021-06-07 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CedulaForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resident_number', models.CharField(max_length=100)),
                ('request_number', models.CharField(max_length=100)),
                ('birth_place', models.CharField(max_length=100)),
                ('profession', models.CharField(blank=True, max_length=100, null=True)),
                ('monthly_income', models.CharField(blank=True, max_length=100, null=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('approval', models.BooleanField(default=False)),
            ],
        ),
    ]
