# Generated by Django 3.2.9 on 2022-03-05 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BailBond',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_number', models.CharField(max_length=100, unique=True)),
                ('case_number', models.PositiveIntegerField(default=0, unique=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('approval', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='BarangayClearance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_number', models.CharField(max_length=100, unique=True)),
                ('purpose', models.CharField(choices=[('Loan', 'Loan'), ('Others', 'Others')], max_length=10, null=True)),
                ('has_payment', models.BooleanField(default=False)),
                ('is_paid', models.BooleanField(default=False)),
                ('approval', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='BuildingClearance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_number', models.CharField(max_length=100, unique=True)),
                ('maintenance_type', models.CharField(max_length=100)),
                ('approval', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='BusinessClearance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_number', models.CharField(max_length=100, unique=True)),
                ('business_name', models.CharField(max_length=100)),
                ('business_owner', models.CharField(max_length=100)),
                ('business_address', models.CharField(max_length=100)),
                ('business_nature', models.CharField(max_length=100)),
                ('start_business_operated', models.DateField()),
                ('approval', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='BusinessClosure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_number', models.CharField(max_length=100, unique=True)),
                ('business_name', models.CharField(max_length=100)),
                ('business_owner', models.CharField(max_length=100)),
                ('business_address', models.CharField(max_length=100)),
                ('business_nature', models.CharField(max_length=100)),
                ('last_business_operated', models.DateField()),
                ('approval', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Cedula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_number', models.CharField(max_length=100, unique=True)),
                ('birth_place', models.CharField(max_length=100)),
                ('profession', models.CharField(blank=True, max_length=100, null=True)),
                ('monthly_income', models.PositiveIntegerField(blank=True, default=0)),
                ('is_paid', models.BooleanField(default=False)),
                ('approval', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Comelec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_number', models.CharField(max_length=100, unique=True)),
                ('approval', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ConstituentID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_number', models.CharField(max_length=100, unique=True)),
                ('id_number', models.PositiveIntegerField(default=0, unique=True)),
                ('date_received', models.DateField()),
                ('signature', models.ImageField(null=True, upload_to='signature/%Y/%m/%D/')),
                ('picture', models.ImageField(null=True, upload_to='pic/%Y/%m/%D/')),
                ('is_paid', models.BooleanField(default=False)),
                ('approval', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='DentalService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_number', models.CharField(max_length=100, unique=True)),
                ('approval', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Guardianship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_number', models.CharField(max_length=100, unique=True)),
                ('guardian_name', models.CharField(max_length=100)),
                ('approval', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Immunization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_number', models.CharField(max_length=100, unique=True)),
                ('mother_name', models.CharField(max_length=100)),
                ('father_name', models.CharField(max_length=100)),
                ('birth_height', models.PositiveIntegerField(default=0)),
                ('birth_weight', models.PositiveIntegerField(default=0)),
                ('approval', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='IndigencyBurial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_number', models.CharField(max_length=100, unique=True)),
                ('deceased_relationship', models.CharField(choices=[('Father', 'Father'), ('Mother', 'Mother'), ('Son', 'Son'), ('Daughter', 'Daughter'), ('Others', 'Others')], max_length=100)),
                ('deceased_name', models.CharField(max_length=100)),
                ('passed_onto_whom', models.CharField(max_length=100)),
                ('approval', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='IndigencyClearance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_number', models.CharField(max_length=100, unique=True)),
                ('patient_relationship', models.CharField(choices=[('Father', 'Father'), ('Mother', 'Mother'), ('Son', 'Son'), ('Daughter', 'Daughter'), ('Others', 'Others')], max_length=100)),
                ('patient_name', models.CharField(max_length=100)),
                ('purpose', models.CharField(max_length=100)),
                ('passed_onto_whom', models.CharField(max_length=100)),
                ('approval', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MaternalCare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_number', models.CharField(max_length=100, unique=True)),
                ('child_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('birth_place', models.CharField(max_length=100)),
                ('approval', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Residency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_number', models.CharField(max_length=100, unique=True)),
                ('approval', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_number', models.CharField(max_length=100, unique=True)),
                ('student_name', models.CharField(max_length=100)),
                ('parent_name', models.CharField(max_length=100)),
                ('school', models.CharField(max_length=100)),
                ('grade', models.PositiveIntegerField(default=0)),
                ('approval', models.BooleanField(default=False)),
            ],
        ),
    ]
