# Generated by Django 3.2.3 on 2021-06-07 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Forms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildingClearanceForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resident_number', models.CharField(max_length=100)),
                ('request_number', models.CharField(max_length=100)),
                ('maintenance_type', models.CharField(max_length=100)),
                ('approval', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ConstituentIDForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resident_number', models.CharField(max_length=100)),
                ('request_number', models.CharField(max_length=100)),
                ('id_number', models.CharField(max_length=100, unique=True)),
                ('date_received', models.DateField(auto_now_add=True)),
                ('signature', models.URLField()),
                ('picture', models.URLField(null=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('approval', models.BooleanField(default=False)),
            ],
        ),
    ]
