# Generated by Django 3.2.3 on 2021-06-07 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Forms', '0002_buildingclearanceform_constituentidform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildingclearanceform',
            name='request_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cedulaform',
            name='monthly_income',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='cedulaform',
            name='request_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='constituentidform',
            name='date_received',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='constituentidform',
            name='id_number',
            field=models.IntegerField(default=0, unique=True),
        ),
        migrations.AlterField(
            model_name='constituentidform',
            name='request_number',
            field=models.IntegerField(default=0),
        ),
    ]
