# Generated by Django 3.2.3 on 2021-06-07 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Forms', '0003_auto_20210607_2300'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BuildingClearanceForm',
            new_name='BuildingClearance',
        ),
        migrations.RenameModel(
            old_name='CedulaForm',
            new_name='Cedula',
        ),
        migrations.RenameModel(
            old_name='ConstituentIDForm',
            new_name='ConstituentID',
        ),
    ]
