# Generated by Django 3.2.3 on 2021-06-07 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Forms', '0004_auto_20210607_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildingclearance',
            name='request_number',
            field=models.IntegerField(default=0, unique=True),
        ),
        migrations.AlterField(
            model_name='buildingclearance',
            name='resident_number',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='cedula',
            name='request_number',
            field=models.IntegerField(default=0, unique=True),
        ),
        migrations.AlterField(
            model_name='cedula',
            name='resident_number',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='constituentid',
            name='request_number',
            field=models.IntegerField(default=0, unique=True),
        ),
        migrations.AlterField(
            model_name='constituentid',
            name='resident_number',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
