# Generated by Django 3.2.3 on 2021-06-07 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Forms', '0005_auto_20210607_2347'),
    ]

    operations = [
        migrations.CreateModel(
            name='BarangayClearance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resident_number', models.CharField(max_length=100, unique=True)),
                ('request_number', models.IntegerField(default=0, unique=True)),
                ('has_payment', models.BooleanField(default=False)),
                ('is_paid', models.BooleanField(default=False)),
                ('approval', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Residency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resident_number', models.CharField(max_length=100, unique=True)),
                ('request_number', models.IntegerField(default=0, unique=True)),
                ('approval', models.BooleanField(default=False)),
            ],
        ),
    ]
