# Generated by Django 3.2.3 on 2021-06-07 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Forms', '0006_barangayclearance_residency'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessClosure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resident_number', models.CharField(max_length=100, unique=True)),
                ('request_number', models.IntegerField(default=0, unique=True)),
                ('business_name', models.CharField(max_length=100)),
                ('business_owner', models.CharField(max_length=100)),
                ('business_address', models.CharField(max_length=100)),
                ('business_nature', models.CharField(max_length=100)),
                ('last_business_operated', models.DateField()),
                ('approval', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Comelec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resident_number', models.CharField(max_length=100, unique=True)),
                ('request_number', models.IntegerField(default=0, unique=True)),
                ('approval', models.BooleanField(default=False)),
            ],
        ),
    ]
