# Generated by Django 3.2.3 on 2021-06-07 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Forms', '0007_businessclosure_comelec'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constituentid',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='pic/%Y/%m/%D/'),
        ),
        migrations.AlterField(
            model_name='constituentid',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='signature/%Y/%m/%D/'),
        ),
    ]
