# Generated by Django 3.2.3 on 2021-06-07 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Forms', '0008_auto_20210608_0100'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConstituentID',
        ),
    ]
