# Generated by Django 3.2.3 on 2021-06-07 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Forms', '0009_delete_constituentid'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConstituentID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resident_number', models.CharField(max_length=100, unique=True)),
                ('request_number', models.IntegerField(default=0, unique=True)),
                ('id_number', models.IntegerField(default=0, unique=True)),
                ('date_received', models.DateField()),
                ('signature', models.ImageField(blank=True, null=True, upload_to='signature/%Y/%m/%D/')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='pic/%Y/%m/%D/')),
                ('is_paid', models.BooleanField(default=False)),
                ('approval', models.BooleanField(default=False)),
            ],
        ),
    ]
