# Generated by Django 3.2.3 on 2021-06-07 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Forms', '0010_constituentid'),
    ]

    operations = [
        migrations.CreateModel(
            name='BailBond',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resident_number', models.CharField(max_length=100, unique=True)),
                ('request_number', models.IntegerField(default=0, unique=True)),
                ('case_number', models.IntegerField(default=0, unique=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('approval', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='BusinessClearance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resident_number', models.CharField(max_length=100, unique=True)),
                ('request_number', models.IntegerField(default=0, unique=True)),
                ('business_name', models.CharField(max_length=100)),
                ('business_owner', models.CharField(max_length=100)),
                ('business_address', models.CharField(max_length=100)),
                ('business_nature', models.CharField(max_length=100)),
                ('start_business_operated', models.DateField()),
                ('approval', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='DentalService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resident_number', models.CharField(max_length=100, unique=True)),
                ('request_number', models.IntegerField(default=0, unique=True)),
                ('approval', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Guardianship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resident_number', models.CharField(max_length=100, unique=True)),
                ('request_number', models.IntegerField(default=0, unique=True)),
                ('guardian_name', models.CharField(max_length=100)),
                ('approval', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ImmunizationForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resident_number', models.CharField(max_length=100, unique=True)),
                ('request_number', models.IntegerField(default=0, unique=True)),
                ('mother_name', models.CharField(max_length=100)),
                ('father_name', models.CharField(max_length=100)),
                ('birth_height', models.IntegerField(default=0)),
                ('birth_weight', models.IntegerField(default=0)),
                ('approval', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='IndigencyBurial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resident_number', models.CharField(max_length=100, unique=True)),
                ('request_number', models.IntegerField(default=0, unique=True)),
                ('deceased_relationship', models.CharField(max_length=100)),
                ('deceased_name', models.CharField(max_length=100)),
                ('passed_onto_whom', models.CharField(max_length=100)),
                ('approval', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='IndigencyClearance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resident_number', models.CharField(max_length=100, unique=True)),
                ('request_number', models.IntegerField(default=0, unique=True)),
                ('patient_relationship', models.CharField(max_length=100)),
                ('patient_name', models.CharField(max_length=100)),
                ('purpose', models.CharField(max_length=100)),
                ('passed_onto_whom', models.CharField(max_length=100)),
                ('approval', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MaternalCare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resident_number', models.CharField(max_length=100, unique=True)),
                ('request_number', models.IntegerField(default=0, unique=True)),
                ('child_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('birth_place', models.CharField(max_length=100)),
                ('approval', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='VoucherForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resident_number', models.CharField(max_length=100, unique=True)),
                ('request_number', models.IntegerField(default=0, unique=True)),
                ('student_name', models.CharField(max_length=100)),
                ('parent_name', models.CharField(max_length=100)),
                ('school', models.CharField(max_length=100)),
                ('grade', models.IntegerField(default=0)),
                ('approval', models.BooleanField(default=False)),
            ],
        ),
    ]
