# Generated by Django 3.2.4 on 2021-06-08 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Forms', '0011_bailbond_businessclearance_dentalservice_guardianship_immunizationform_indigencyburial_indigencyclea'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ImmunizationForm',
            new_name='Immunization',
        ),
        migrations.RenameModel(
            old_name='VoucherForm',
            new_name='Voucher',
        ),
    ]
