# Generated by Django 3.2.3 on 2021-06-08 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Forms', '0015_alter_cedula_resident_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cedula',
            name='resident_number',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
