# Generated by Django 3.2.3 on 2021-06-08 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UsersApp', '0003_auto_20210529_2133'),
        ('Forms', '0017_alter_cedula_resident_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bailbond',
            name='resident_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UsersApp.userinformation'),
        ),
        migrations.AlterField(
            model_name='barangayclearance',
            name='resident_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UsersApp.userinformation'),
        ),
        migrations.AlterField(
            model_name='buildingclearance',
            name='resident_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UsersApp.userinformation'),
        ),
        migrations.AlterField(
            model_name='businessclearance',
            name='resident_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UsersApp.userinformation'),
        ),
        migrations.AlterField(
            model_name='businessclosure',
            name='resident_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UsersApp.userinformation'),
        ),
        migrations.AlterField(
            model_name='comelec',
            name='resident_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UsersApp.userinformation'),
        ),
        migrations.AlterField(
            model_name='constituentid',
            name='resident_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UsersApp.userinformation'),
        ),
        migrations.AlterField(
            model_name='dentalservice',
            name='resident_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UsersApp.userinformation'),
        ),
        migrations.AlterField(
            model_name='guardianship',
            name='resident_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UsersApp.userinformation'),
        ),
        migrations.AlterField(
            model_name='immunization',
            name='resident_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UsersApp.userinformation'),
        ),
        migrations.AlterField(
            model_name='indigencyburial',
            name='resident_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UsersApp.userinformation'),
        ),
        migrations.AlterField(
            model_name='indigencyclearance',
            name='resident_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UsersApp.userinformation'),
        ),
        migrations.AlterField(
            model_name='maternalcare',
            name='resident_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UsersApp.userinformation'),
        ),
        migrations.AlterField(
            model_name='residency',
            name='resident_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UsersApp.userinformation'),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='resident_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UsersApp.userinformation'),
        ),
    ]
