# Generated by Django 3.2.3 on 2021-06-08 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Forms', '0018_auto_20210608_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cedula',
            name='monthly_income',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='constituentid',
            name='picture',
            field=models.ImageField(null=True, upload_to='pic/%Y/%m/%D/'),
        ),
        migrations.AlterField(
            model_name='constituentid',
            name='signature',
            field=models.ImageField(null=True, upload_to='signature/%Y/%m/%D/'),
        ),
    ]
