# Generated by Django 3.2.3 on 2021-06-08 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Forms', '0019_auto_20210608_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bailbond',
            name='case_number',
            field=models.PositiveIntegerField(default=0, unique=True),
        ),
        migrations.AlterField(
            model_name='bailbond',
            name='request_number',
            field=models.PositiveIntegerField(default=0, unique=True),
        ),
        migrations.AlterField(
            model_name='barangayclearance',
            name='request_number',
            field=models.PositiveIntegerField(default=0, unique=True),
        ),
        migrations.AlterField(
            model_name='buildingclearance',
            name='request_number',
            field=models.PositiveIntegerField(default=0, unique=True),
        ),
        migrations.AlterField(
            model_name='businessclearance',
            name='request_number',
            field=models.PositiveIntegerField(default=0, unique=True),
        ),
        migrations.AlterField(
            model_name='businessclosure',
            name='request_number',
            field=models.PositiveIntegerField(default=0, unique=True),
        ),
        migrations.AlterField(
            model_name='cedula',
            name='monthly_income',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='cedula',
            name='request_number',
            field=models.PositiveIntegerField(default=0, unique=True),
        ),
        migrations.AlterField(
            model_name='comelec',
            name='request_number',
            field=models.PositiveIntegerField(default=0, unique=True),
        ),
        migrations.AlterField(
            model_name='constituentid',
            name='id_number',
            field=models.PositiveIntegerField(default=0, unique=True),
        ),
        migrations.AlterField(
            model_name='constituentid',
            name='request_number',
            field=models.PositiveIntegerField(default=0, unique=True),
        ),
        migrations.AlterField(
            model_name='dentalservice',
            name='request_number',
            field=models.PositiveIntegerField(default=0, unique=True),
        ),
        migrations.AlterField(
            model_name='guardianship',
            name='request_number',
            field=models.PositiveIntegerField(default=0, unique=True),
        ),
        migrations.AlterField(
            model_name='immunization',
            name='birth_height',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='immunization',
            name='birth_weight',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='immunization',
            name='request_number',
            field=models.PositiveIntegerField(default=0, unique=True),
        ),
        migrations.AlterField(
            model_name='indigencyburial',
            name='request_number',
            field=models.PositiveIntegerField(default=0, unique=True),
        ),
        migrations.AlterField(
            model_name='indigencyclearance',
            name='request_number',
            field=models.PositiveIntegerField(default=0, unique=True),
        ),
        migrations.AlterField(
            model_name='maternalcare',
            name='request_number',
            field=models.PositiveIntegerField(default=0, unique=True),
        ),
        migrations.AlterField(
            model_name='residency',
            name='request_number',
            field=models.PositiveIntegerField(default=0, unique=True),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='grade',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='request_number',
            field=models.PositiveIntegerField(default=0, unique=True),
        ),
    ]
