# Generated by Django 3.2.3 on 2021-06-08 12:17

import Forms.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Forms', '0020_auto_20210608_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessclearance',
            name='request_number',
            field=models.PositiveIntegerField(default=0, unique=True),
        ),
    ]
