# Generated by Django 3.2.3 on 2021-06-08 12:22

import Forms.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Forms', '0021_alter_businessclearance_request_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bailbond',
            name='request_number',
            field=models.PositiveIntegerField(default=0, unique=True),
        ),
        migrations.AlterField(
            model_name='barangayclearance',
            name='request_number',
            field=models.PositiveIntegerField(default=0, unique=True),
        ),
        migrations.AlterField(
            model_name='buildingclearance',
            name='request_number',
            field=models.PositiveIntegerField(default=0, unique=True),
        ),
        migrations.AlterField(
            model_name='businessclosure',
            name='request_number',
            field=models.PositiveIntegerField(default=0, unique=True),
        ),
        migrations.AlterField(
            model_name='cedula',
            name='request_number',
            field=models.PositiveIntegerField(default=0, unique=True),
        ),
        migrations.AlterField(
            model_name='comelec',
            name='request_number',
            field=models.PositiveIntegerField(default=0, unique=True),
        ),
        migrations.AlterField(
            model_name='constituentid',
            name='request_number',
            field=models.PositiveIntegerField(default=0, unique=True),
        ),
        migrations.AlterField(
            model_name='dentalservice',
            name='request_number',
            field=models.PositiveIntegerField(default=0, unique=True),
        ),
        migrations.AlterField(
            model_name='guardianship',
            name='request_number',
            field=models.PositiveIntegerField(default=0, unique=True),
        ),
        migrations.AlterField(
            model_name='immunization',
            name='request_number',
            field=models.PositiveIntegerField(default=0, unique=True),
        ),
        migrations.AlterField(
            model_name='indigencyburial',
            name='request_number',
            field=models.PositiveIntegerField(default=0, unique=True),
        ),
        migrations.AlterField(
            model_name='indigencyclearance',
            name='request_number',
            field=models.PositiveIntegerField(default=0, unique=True),
        ),
        migrations.AlterField(
            model_name='maternalcare',
            name='request_number',
            field=models.PositiveIntegerField(default=0, unique=True),
        ),
        migrations.AlterField(
            model_name='residency',
            name='request_number',
            field=models.PositiveIntegerField(default=0, unique=True),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='request_number',
            field=models.PositiveIntegerField(default=0, unique=True),
        ),
    ]
