# Generated by Django 3.2.3 on 2021-06-08 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Forms', '0022_auto_20210608_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='barangayclearance',
            name='purpose',
            field=models.CharField(choices=[('Loan', 'Loan'), ('Others', 'Others')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='barangayclearance',
            name='has_payment',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
