# Generated by Django 3.2.3 on 2021-06-08 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Forms', '0023_auto_20210609_0158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barangayclearance',
            name='has_payment',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='indigencyburial',
            name='deceased_relationship',
            field=models.CharField(choices=[('Father', 'Father'), ('Mother', 'Mother'), ('Son', 'Son'), ('Daughter', 'Daughter'), ('Others', 'Others')], max_length=100),
        ),
        migrations.AlterField(
            model_name='indigencyclearance',
            name='patient_relationship',
            field=models.CharField(choices=[('Father', 'Father'), ('Mother', 'Mother'), ('Son', 'Son'), ('Daughter', 'Daughter'), ('Others', 'Others')], max_length=100),
        ),
    ]
