# Generated by Django 3.2.3 on 2021-06-09 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UsersApp', '0013_userinformation_age'),
        ('Forms', '0025_auto_20210609_0336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cedula',
            name='resident_number',
            field=models.ForeignKey(limit_choices_to={'resident_number': True}, on_delete=django.db.models.deletion.CASCADE, to='UsersApp.userinformation'),
        ),
    ]
