# Generated by Django 3.2.3 on 2021-06-09 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UsersApp', '0014_auto_20210609_1635'),
        ('Forms', '0026_alter_cedula_resident_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cedula',
            name='resident_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UsersApp.userinformation'),
        ),
    ]
