# Generated by Django 3.2.9 on 2021-11-09 02:23

import UsersApp.models
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='email')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('mobile_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('resident_number', models.CharField(max_length=100, null=True)),
                ('date_of_birth', models.DateField(null=True)),
                ('age', models.SmallIntegerField(null=True, validators=[UsersApp.models.User.validate_num])),
                ('gender', models.CharField(choices=[('F', 'Female'), ('M', 'Male')], max_length=1, null=True)),
                ('province', models.CharField(choices=[('Metro Manila', 'Metro Manila'), ('Abra', 'Abra'), ('Agusan Del Norte', 'Agusan Del Norte'), ('Agusan Del Sur', 'Agusan Del Sur'), ('Aklan', 'Aklan'), ('Albay', 'Albay'), ('Antique', 'Antique'), ('Apayao', 'Apayao'), ('Aurora', 'Aurora'), ('Basilan', 'Basilan'), ('Bataan', 'Bataan'), ('Batanes', 'Batanes'), ('Batangas', 'Batangas'), ('Benguet', 'Benguet'), ('Biliran', 'Biliran'), ('Bohol', 'Bohol'), ('Bukidnon', 'Bukidnon'), ('Bulacan', 'Bulacan'), ('Cagayan', 'Cagayan'), ('Camarines Norte', 'Camarines Norte'), ('Camarines Sur', 'Camarines Sur'), ('Camiguin', 'Camiguin'), ('Capiz', 'Capiz'), ('Catanduanes', 'Catanduanes'), ('Cavite', 'Cavite'), ('Cebu', 'Cebu'), ('Compostella Valley', 'Compostella Valley'), ('Cotabato', 'Cotabato'), ('Davao Del Norte', 'Davao Del Norte'), ('Davao Del Sur', 'Davao Del Sur'), ('Davao Occidental', 'Davao Occidental'), ('Davao Oriental', 'Davao Oriental'), ('Dinagat Islands', 'Dinagat Islands'), ('Eastern Samar', 'Eastern Samar'), ('Guimaras', 'Guimaras'), ('Ifugao', 'Ifugao'), ('Ilocos Norte', 'Ilocos Norte'), ('Ilocos Sur', 'Ilocos Sur'), ('Iloilo', 'Iloilo'), ('Isabela', 'Isabela'), ('Kalinga', 'Kalinga'), ('La Union', 'La Union'), ('Laguna', 'Laguna'), ('Lanao Del Norte', 'Lanao Del Norte'), ('Lanao Del Sur', 'Lanao Del Sur'), ('Leyte', 'Leyte'), ('Maguindanao', 'Maguindanao'), ('Marinduque', 'Marinduque'), ('Masbate', 'Masbate'), ('Misamis Occidental', 'Misamis Occidental'), ('Misamis Oriental', 'Misamis Oriental'), ('Mountain Province', 'Mountain Province'), ('Negros Occidental', 'Negros Occidental'), ('Negros Oriental', 'Negros Oriental'), ('Northern Samar', 'Northern Samar'), ('Nueva Ecija', 'Nueva Ecija'), ('Nueva Vizcaya', 'Nueva Vizcaya'), ('Occidental Mindoro', 'Occidental Mindoro'), ('Oriental Mindoro', 'Oriental Mindoro'), ('Palawan', 'Palawan'), ('Pampanga', 'Pampanga'), ('Pangasinan', 'Pangasinan'), ('Quezon', 'Quezon'), ('Quirino', 'Quirino'), ('Rizal', 'Rizal'), ('Romblon', 'Romblon'), ('Samar', 'Samar'), ('Sarangani', 'Sarangani'), ('Siquijor', 'Siquijor'), ('Sorsogon', 'Sorsogon'), ('South Cotabato', 'South Cotabato'), ('Southern Leyte', 'Southern Leyte'), ('Sultan Kudarat', 'Sultan Kudarat'), ('Sulu', 'Sulu'), ('Surigao Del Norte', 'Surigao Del Norte'), ('Surigao Del Sur', 'Surigao Del Sur'), ('Tarlac', 'Tarlac'), ('Tawi-Tawi', 'Tawi-Tawi'), ('Zambales', 'Zambales'), ('Zamboanga Del Norte', 'Zamboanga Del Norte'), ('Zamboanga Del Sur', 'Zamboanga Del Sur'), ('Zamboanga Sibugay', 'Zamboanga Sibugay')], max_length=50, null=True)),
                ('civil_status', models.CharField(choices=[('CIVIL_MARRIED', 'Married'), ('CIVIL_SINGLE', 'Single'), ('CIVIL_DIVORCED', 'Divorced'), ('CIVIL_WIDOWED', 'Widowed')], max_length=50, null=True)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='profilepic/%Y/%m/%D/')),
                ('id_pic', models.ImageField(blank=True, null=True, upload_to='id_pic/%Y/%m/%D/')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
