# Generated by Django 3.2.3 on 2021-06-08 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UsersApp', '0003_auto_20210529_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinformation',
            name='request_number',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
