# Generated by Django 3.2.3 on 2021-06-08 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UsersApp', '0004_userinformation_request_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinformation',
            old_name='request_number',
            new_name='resident_number',
        ),
    ]
