# Generated by Django 3.2.4 on 2021-11-15 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UsersApp', '0004_auto_20211114_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='province',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
