# Generated by Django 3.2.9 on 2022-02-16 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UsersApp', '0005_alter_user_province'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='resident_number',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
