# Generated by Django 3.2.3 on 2021-06-08 17:37

import UsersApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UsersApp', '0005_rename_request_number_userinformation_resident_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinformation',
            name='age',
            field=models.SmallIntegerField(null=True, validators=[UsersApp.models.UserInformation.validate_num]),
        ),
        migrations.AddField(
            model_name='userinformation',
            name='birth_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='userinformation',
            name='civil_status',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userinformation',
            name='gender',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='userinformation',
            name='province',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
