# Generated by Django 3.2.3 on 2021-06-08 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UsersApp', '0008_alter_userinformation_civil_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinformation',
            name='age',
        ),
    ]
