# Generated by Django 3.2.3 on 2021-06-08 18:35

import UsersApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UsersApp', '0009_remove_userinformation_age'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userinformation',
            options={},
        ),
        migrations.AddField(
            model_name='userinformation',
            name='age',
            field=models.SmallIntegerField(null=True, validators=[UsersApp.models.UserInformation.validate_num]),
        ),
    ]
