# Generated by Django 3.2.3 on 2021-06-08 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UsersApp', '0010_auto_20210609_0235'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinformation',
            old_name='birth_date',
            new_name='date_of_birth',
        ),
    ]
