# Generated by Django 3.2.3 on 2021-06-08 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UsersApp', '0011_rename_birth_date_userinformation_date_of_birth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinformation',
            name='age',
        ),
    ]
