# Generated by Django 3.2.3 on 2021-06-09 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UsersApp', '0014_auto_20210609_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinformation',
            name='UserName',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
