# Generated by Django 3.2.3 on 2021-06-09 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UsersApp', '0015_userinformation_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformation',
            name='UserName',
            field=models.CharField(default='', max_length=100),
        ),
    ]
