# Generated by Django 3.2.4 on 2021-06-13 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UsersApp', '0018_auto_20210611_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='resident_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
