# Generated by Django 3.2.4 on 2021-06-13 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UsersApp', '0019_auto_20210613_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformation',
            name='resident_number',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
