# Generated by Django 3.2.4 on 2021-10-13 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UsersApp', '0019_auto_20210704_1734'),
        ('UsersApp', '0020_alter_userinformation_resident_number'),
    ]

    operations = [
    ]
