# Generated by Django 3.2.9 on 2021-11-14 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UsersApp', '0003_auto_20211114_1151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id_pic',
        ),
        migrations.RemoveField(
            model_name='user',
            name='profile_pic',
        ),
    ]
