from django.urls import path
from .views import *
from Forms import views

urlpatterns = [
    path('cedula/', CedulaList.as_view()),
    path('mycedula/', CedulaView.as_view()),
    path('constituent/', ConstituentIDList.as_view()),
    path('myconstituent/', ConstituentIDView.as_view()),
    path('building/', BuildingClearanceList.as_view()),
    path('mybuilding/', BuildingClearanceView.as_view()),
    path('residency/', ResidencyList.as_view()),
    path('myresidency/', ResidencyView.as_view()),
    path('barangay-clearance/', BarangayClearanceList.as_view()),
    path('mybarangay-clearance/', BarangayClearanceView.as_view()),
    path('comelec/', ComelecList.as_view()),
    path('mycomelec/', ComelecView.as_view()),
    path('business-closure/', BusinessClosureList.as_view()),
    path('mybusiness-closure/', BusinessClosureView.as_view()),
    path('bailbond/', BailBondList.as_view()),
    path('mybailbond/', BailBondView.as_view()),
    path('guardianship/', GuardianshipList.as_view()),
    path('myguardianship/', GuardianshipView.as_view()),
    path('indigency-burial/', IndigencyBurialList.as_view()),
    path('myindigency-burial/', IndigencyBurialView.as_view()),
    path('indigency-clearance/', IndigencyClearanceList.as_view()),
    path('myindigency-clearance/', IndigencyClearanceView.as_view()),
    path('voucher/', VoucherList.as_view()),
    path('myvoucher/', VoucherView.as_view()),
    path('business-clearance/', BusinessClearanceList.as_view()),
    path('mybusiness-clearance/', BusinessClearanceView.as_view()),
    path('immunization/', ImmunizationList.as_view()),
    path('myimmunization/', ImmunizationView.as_view()),
    path('dental-service/', DentalServiceList.as_view()),
    path('mydental-service/', DentalServiceView.as_view()),
    path('maternal-care/', MaternalCareList.as_view()),
    path('mymaternal-care/', MaternalCareView.as_view()),
    path('email_notification', views.email_notification),
    path('view-all-myforms/', AllFormsView.as_view()),
]